import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  AppBar,
  Avatar,
  Box,
  Container,
  Grid,
  TextField,
  Toolbar,
  Typography,
  Button,
  Table,
  Paper,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@mui/material";
import { deepOrange } from "@mui/material/colors";
import { Header } from "@/components/Header";
import { Login } from "@/components/Login";
import { useGlobalContext } from "@/contexts";
import { Products } from "@/components/Products";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { isLogin } = useGlobalContext();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {!isLogin ? <Login /> : <Products />}
      </main>
    </>
  );
}
